- package.json
Reduced description for the next release to avoid it getting clipped.
> Reduce description lenght

- .github/ISSUE_TEMPLATE/---bug-report.md
- .github/ISSUE_TEMPLATE/---feature-request.md
- .github/pull_request_template.md
The aim is to add templates for issues and PRs.
Related: #21
> Adds issue and pr templates. Related #21

- .github/pull_request_template.md
- contributing.md
Update contributing guide
Related: #21
> Updates contributing guide

- .github/workflows/update-samples.yml
- .gitignore
- scripts/prepare-sample-data.ps1
The aim is to add small fixup in sample pipeline
Related: #6
> Fixup for sample pipeline

- package-lock.json
- package.json
The aim is to add dependency that will support creating SPFx solutions
Closes: #49
> Adds dependency to support writing spfx code

- CHANGELOG.md
- package-lock.json
- package.json
The aim is to update CLI for Microsoft 365 dependency and add support for SPFx 1.17.4
Closes: #52
> Release v1.1.0

- package-lock.json
- package.json
> Prepare pre release

- src/panels/CommandPanel.ts
The aim is to refactor help and feedbakc section to reoder links and add more learning path links
Closes: #77
> Refactors help and feedback section. Closes: #77

- package.json
- src/constants/Commands.ts
- src/constants/ContextKeys.ts
- src/panels/CommandPanel.ts
- src/services/CliActions.ts
The aim is to add a new action which will allow to grant API permissions.
Closes: #8
> Adds grant API permissions action. Closes: #8

- package-lock.json
- package.json
- src/constants/Commands.ts
- src/panels/CommandPanel.ts
- src/services/CliActions.ts
The aim is to add a new action that will generate a CI/CD GitHub workflow
Closes: #44
> Adds a generate CI CD GitHub workflow action. Closes: #44

- src/providers/AuthProvider.ts
Is to fix strange error showing on log in
Closes: #87
> Fixes log in error. Closes #87

- src/panels/CommandPanel.ts
The aim is to update the link to vscode extension wiki.
Closes #89
> Updates link to wiki. Closes #89

- package-lock.json
- package.json
> Updates postcss

- package-lock.json
- package.json
- src/services/CliActions.ts
- src/services/Dependencies.ts
Fixup in validating node version and grant api action.
Closes: #129
> Fix node validation and grant api action. Closes #129

- CHANGELOG.md
- data/sp-dev-fx-aces-samples.json
- data/sp-dev-fx-extensions-samples.json
- data/sp-dev-fx-webparts-samples.json
- package-lock.json
- package.json
- scripts/cli-for-microsoft365-cleanup.ps1
- src/services/CliActions.ts
- src/services/Dependencies.ts
> Release v2.2.0

- CHANGELOG.md
- package-lock.json
- package.json
- src/services/Dependencies.ts
> Release v2.3.0

- src/services/Dependencies.ts
is to add support for SPFx 1.18.2
> Adds support for SPFx 1.18.2

- src/webview/view/components/gallery/GalleryView.tsx
- src/webview/view/components/gallery/SearchBar.tsx
- src/webview/view/hooks/useSamples.tsx
The aim of this PR is to add a 'only scenarios' filter option.
Closes: #165
> Adds only scenarios filter option. Closes: #165

- src/panels/CommandPanel.ts
Adds SPE VS Code extension link to help and feedback.
Closes:  #166
> Adds SPE VS Code extension link to help and feedback. Closes:  #166

- src/constants/Commands.ts
- src/constants/GenerateWorkflowCommandInput.ts
- src/constants/WebViewTypes.ts
- src/constants/WebviewCommand.ts
- src/constants/index.ts
- src/models/YoRc.ts
- src/panels/CommandPanel.ts
- src/services/AdaptiveCardCheck.ts
- src/services/CliActions.ts
- src/utils/index.ts
- src/utils/parseYoRc.ts
- src/webview/PnPWebview.ts
- src/webview/view/components/App.tsx
- src/webview/view/components/forms/workflow/ScaffoldWorkflowView.tsx
- src/webview/view/components/gallery/DetailsView.tsx
- src/webview/view/components/gallery/GalleryHeader.tsx
- src/webview/view/components/gallery/GalleryLoader.tsx
- src/webview/view/components/gallery/GalleryView.tsx
- src/webview/view/components/gallery/List.tsx
- src/webview/view/components/gallery/NoResults.tsx
- src/webview/view/components/icons/RocketIcon.tsx
- src/webview/view/components/icons/index.ts
- src/webview/view/index.css
- src/webview/view/index.tsx
The aim of this PR is to refactor CI/CD workflow action to base on form for scaffolding and not QA popups
#125
> Refactor CI/CD Workflow Action to form based.

- .github/workflows/release-beta.yml
- .github/workflows/release-local.yml
- .github/workflows/release.yml
- .github/workflows/update-samples.yml
Updates pipelines definitions to v4 and removes CLI cleanup step
> Updates pipelines definitions

- src/webview/view/components/forms/workflow/ScaffoldWorkflowView.tsx
Adds a link to newly created app registration and updates the create workflow button name if a new app should be created
Closes: #125
> Adds link to newly registered app

- src/constants/ExtensionTypes.ts
- src/constants/SpfxAddComponentCommandInput.ts
- src/constants/SpfxScaffoldCommandInput.ts
- src/constants/WebViewTypes.ts
- src/constants/WebviewCommand.ts
- src/constants/index.ts
- src/services/Scaffolder.ts
- src/webview/PnPWebview.ts
- src/webview/view/components/App.tsx
- src/webview/view/components/forms/spfxProject/ScaffoldSpfxProjectView.tsx
- src/webview/view/components/icons/AddIcon.tsx
- src/webview/view/components/icons/FolderIcon.tsx
- src/webview/view/components/icons/index.ts
- src/webview/view/index.tsx
is to add a scaffolding form for the add new project action
related: #124
> Refactors scaffolding action to be based on form

- src/constants/ProjectFileContent.ts
- src/constants/SpfxScaffoldCommandInput.ts
- src/extension.ts
- src/services/Scaffolder.ts
- src/webview/view/components/forms/spfxProject/ScaffoldSpfxProjectView.tsx
Is to extend the scaffolding form with custom steps
Closes: #124
> Adds custom scaffolding options to the form

- src/webview/view/components/forms/spfxProject/ScaffoldSpfxProjectView.tsx
Adds links to additional dependencies
> Adds links to additional dependencies

- src/webview/view/hooks/useSamples.tsx
Fixes sample gallery query filter
> Fixes sample gallery query filter

- README.md
- contributing.md
- package-lock.json
- package.json
- src/constants/General.ts
- src/webview/PnPWebview.ts
Rebrand to SPFx Toolkit
Closes: #168
> Rebrand to SPFx Toolkit. Closes: #168

- src/services/Dependencies.ts
Add support for SPFx v1.19.0
Closes: #233
> Updates dependency check. Closes: #233

- README.md
- package-lock.json
- package.json
- src/services/Dependencies.ts
Release 3.2.0 that adds SPFx 1.19.0 support
Closes: #233
> Release v3.2.0

- .eslintrc.json
- .github/workflows/release-local.yml
- npm-shrinkwrap.json
- src/constants/ComponentTypes.ts
- src/constants/ExtensionTypes.ts
- src/constants/FrameworkTypes.ts
- src/constants/NodeVersionManagers.ts
- src/constants/ProjectFileContent.ts
- src/constants/WebViewTypes.ts
- src/constants/WorkflowTypes.ts
- src/providers/AuthProvider.ts
- src/services/AdaptiveCardCheck.ts
- src/services/CertificateActions.ts
- src/services/CliActions.ts
- src/services/CliCommandExecuter.ts
- src/services/CommandExecuter.ts
- src/services/DebuggerCheck.ts
- src/services/Dependencies.ts
- src/services/Extension.ts
- src/services/Folders.ts
- src/services/Scaffolder.ts
- src/services/TerminalCommandExecuter.ts
- src/webview/view/components/App.tsx
- src/webview/view/components/controls/MultiSelect.tsx
- src/webview/view/components/forms/spfxProject/AdditionalStep.tsx
- src/webview/view/components/forms/spfxProject/ComponentDetailsStep.tsx
- src/webview/view/components/forms/spfxProject/GeneralInfoStep.tsx
- src/webview/view/components/forms/spfxProject/PackageSelector.tsx
- src/webview/view/components/gallery/SearchBar.tsx
- src/webview/view/hooks/useSamples.tsx
The aim is to do some house cleaning 
Closes: #248, #247
> House cleaning. Closes: #248, #247

- src/constants/AdaptiveCardTypes.ts
- src/services/Scaffolder.ts
- src/webview/PnPWebview.ts
- src/webview/view/components/forms/spfxProject/ComponentDetailsStep.tsx
- src/webview/view/components/forms/spfxProject/ScaffoldSpfxProjectView.tsx
- src/webview/view/index.tsx
align ACE template scaffolding with SPFx 1.19
Closes: #245
> Adds new ACE template. Closes: #245

- README.md
- npm-shrinkwrap.json
- package.json
> Updates Readme

- src/panels/CommandPanel.ts
- src/webview/view/components/forms/entraAppReg/RegisterEntraAppRegView.tsx
The aim is to provide fixup to recently found errors and issues
Closes: #302,  #304
> Adds error handling to init and missing scopes. Closes: #302,  #304

- src/chat/PromptHandlers.ts
Adding the errormessage as output in the chat response
Closes: #376
> 🚀 Enhance error handling in PromptHandlers to display error messages in red markdown

- npm-shrinkwrap.json
- package.json
- src/chat/PromptHandlers.ts
- src/constants/Commands.ts
- src/extension.ts
- src/providers/AuthProvider.ts
- src/services/actions/CopilotActions.ts
- src/utils/sleep.ts
The aim is to update vscode types and approach with latest. Recheck and cleanup what changed. When upgraded vscode we may use latest improvements of how to handle model picking and loading history in chat command. I checked that and unfrotonatly other models than gpt-4o bring totally different responses which are not possible to pars with current logic. Also loading history seems to be lacking some parts we get with current implementation, so those parts are not changed.
Lastly I added action to activate SPFx Copilot from welcome view
Closes: #334
> Updates vscode to latest, small refactor and adds Copilot action to welcome view. Closes #334

- scripts/prepare-sample-data.ps1
Fixup in the script to handle case when we have multiple samples in sample.json files
Closes #399
> Fixes creating samples data json. Closes #399

- npm-shrinkwrap.json
- src/panels/CommandPanel.ts
- src/services/executeWrappers/TerminalCommandExecuter.ts
Aim is to combine three serve tasks into one task (as below)
Option 1 : Serve
Option 2 : Serve no browser
Option 3 : Serve from configuration
Currently there are three serve tasks, and this new feature will combine this into one single task, where user can select the required options. 
Reused the old `serveProject` method name, and modified the logic in it as below, 
Added three new methods, as follows
`serveTaskTypePrompt` which will prompt the user to select the serve task type as below, This will also, Show or hide 'Serve from configuration' option, if it is not available in `serve.json`
`serveFromConfiguration` which will serve the project by executing the specified configuration, and prompts the user to choose a configuration from the `serve.json`
`getServeConfigNames` will get the …
> Combine serve gulp tasks into a single task. Closes #411

- src/services/actions/CliActions.ts
> Fixes App Install/Uninstall issue on root site. Closes #426
> NA
Closes: #426
> Fixes App Install/Uninstall issue on root site. Closes #426

- CHANGELOG.md
I made a small mistake in last release in the way we specify things in the changelog 🤦‍♂️
> Fixup in the changelog

- CHANGELOG.md
- README.md
- npm-shrinkwrap.json
- package.json
- src/constants/Prompts.ts
- src/services/actions/Dependencies.ts
The aim is to add support for SPFx 1.21
Closes: #454
> Adds support for SPFx 1.21. Closes #454

- src/services/actions/CliActions.ts
Fixes setting form customizer list from to root site
Closes: #460
> Fixes setting form customizer list from to root site. Closes #460

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- src/services/actions/Dependencies.ts
The aim is to add support for SPFx 1.21.1
Closes: #470
> Release v4.7.0

- package.json
Update default action for SPFx app to install
Closes: #429
> Update default action for SPFx app to install. Closes #429

- .github/workflows/update-samples.yml
> #481 caused an issue - the update sample data workflow failed to create a pull request. This PR aims to fix that.
> added permission to create pull requests. 

- .eslintrc.json
- .github/workflows/release-beta.yml
- .github/workflows/release-local.yml
- .github/workflows/release.yml
- npm-shrinkwrap.json
- package.json
- postcss.config.js
- scripts/cli-for-microsoft365-copy-local-version.ps1
- src/test/suite/index.ts
- src/webview/view/components/forms/entraAppReg/RegisterEntraAppRegView.tsx
- src/webview/view/components/forms/spfxProject/FormActions.tsx
- src/webview/view/components/forms/workflow/ScaffoldWorkflowView.tsx
- src/webview/view/components/forms/workflow/WorkflowSummary.tsx
- src/webview/view/components/icons/InfoIcon.tsx
- tailwind.config.js
The aim of this PR is to update extension dependencies to the latest version where possible. Unfortunately, as I checked, we are still not able to use ESM version of the CLI for Microsoft 365, so this will need to wait. 
I also did not touch React version as I didn't want to cover to much.
Along the way I did some minor code cleanup and updated the `vsce` package that we use in all of our workflows to current latest. I also removed the package which we not use.
This PR may be a bit harder then the usual once as it would be best to test it locally the same way you would install the VS Code extension from package. In order to do that you will need to:
1. if you have SPFx Toolkit extension installed, then uninstall it
2. pull this branch and remove node_modules
3. run `npm install`
4. run …
> Dependencies updates. Closes #434

- docs/astro.config.mjs
- docs/src/content/docs/index.mdx
Aim is to perform small fixup in the docs
> Updates Docs

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
The aim is to update issue templates to include the additional "👀 needs peer review" label and issue type
Closes: #475
> Updates issue templates. Closes #475

- src/panels/CommandPanel.ts
- src/panels/HelpTreeData.ts
- src/test/suite/extension.test.ts
- src/test/suite/helpView.test.ts
- src/test/testConstants.ts
Adds integration tests for **Help and Feedback** section.
Closes: #418
> Adds integration tests for Help and Feedback section. Closes #418

- .github/workflows/release-docs.yml
- docs/src/components/Introduction.astro
- docs/src/components/YouTubeEmbed.astro
This PR reduces carbon footprint of docs by lazy-loading YouTube video on the landing page. 
Closes: #541
> Reduces carbon footprint of docs. Closes #541

- README.md
- docs/astro.config.mjs
- docs/src/components/Introduction.astro
- docs/src/content/docs/features/scaffolding.mdx
This PR updates **Create new project** feature page.
Closes: #491
> refactor - Create new project

- README.md
- package.json
Added some small updates to increas docs visiblity 
Closes: #543
> Increases-docs-visibility. Closes #543

- contributing.md
- docs/astro.config.mjs
- docs/src/content/docs/contributing-guidance.mdx
This PR updates contribution guidelines in both documentation and wiki.
Closes: #549
> refactor - contribution guidelines. Closes #549

- npm-shrinkwrap.json
- package.json
The aim of this change is to address VS Code Marketplace issues 
https://github.com/microsoft/vscode/issues/269737
> Release v4.10.0
