- .eslintrc.json
- src/webview/view/components/gallery/GalleryView.tsx
- src/webview/view/components/gallery/List.tsx
- src/webview/view/components/gallery/SearchBar.tsx
- src/webview/view/components/icons/SearchIcon.tsx
- src/webview/view/hooks/useSamples.tsx
The aim of this PR is to add search functionality to both samples and scenarios view.
Movie how it works
https://user-images.githubusercontent.com/58668583/215363964-a834e73d-f83c-495a-a5fc-49f234d8acc8.mp4
Closes: #5
> Adds search bar to samples and scenarios views

- package-lock.json
- package.json
The aim of this PR is to add support for SPFx 1.17.1
Closes: #18 
before the change when I had a SPFx solution in  v1.16.1 the viva-vscode upgrade feature did not suggested anything to upgrade
After this change it will guide the user/dev to upgrade to v1.17.1
> Updated CLI for Microsoft 365. Closes #18

- .github/ISSUE_TEMPLATE/---bug-report.md
- .github/ISSUE_TEMPLATE/---feature-request.md
- .github/workflows/release-beta.yml
- CHANGELOG.md
- package-lock.json
- package.json
The aim is to refactor the release process not to base on auto generated numbers in flow. The main reason for that is problem with keeping this in sync with changelog for beta releases which currently is done manually and is usually out of sync. 
Related: #21
> Updates beta release flow

- src/services/Terminal.ts
The aim is to resolve a strange issue of missing first letter in gulp command when booting up terminal of running task.
Closes: #92
> Fixes missing letter in gulp command. Closes: #92

- .github/workflows/release-beta.yml
- .github/workflows/release-local.yml
- .github/workflows/release.yml
- .vscodeignore
- package-lock.json
- package.json
- scripts/cli-for-microsoft365-cleanup.ps1
- scripts/cli-for-microsoft365-copy-local-version.ps1
- src/constants/AdaptiveCardTypes.ts
- src/constants/ExtensionTypes.ts
- src/providers/AuthProvider.ts
- src/services/Dependencies.ts
- src/services/Scaffolder.ts
- src/webview/PnPWebview.ts
- src/webview/view/hooks/useSamples.tsx
The aim of this PR is to refactor the extension to use local version of CLI for Microsoft365 that was reverted to cjs. Mainly due to the fact es modules are still not supported by VS Code extensions.
Along the way some small bug fixes were included like reading sample data from main branch or allowing to login immediately after logout
Closes: #103 
Closes:  #82 
Closes:  #81
> Refactor CLI for M365 dependency to local version and bug fixes. Closes: #103 #82 #81

- src/services/Dependencies.ts
The aim is to check for a specific version of yo (4.3.1) and install this one and not the latest one
installs the correct version of yo which overwrites any other currently installed version
check for the correct version of yo
Closes: #138
> Updates yo validation to check for version 4.3.1. Closes: #138

- package.json
- src/extension.ts
- src/models/YoRc.ts
- src/models/index.ts
- src/panels/CommandPanel.ts
- src/providers/AuthProvider.ts
- src/services/AdaptiveCardCheck.ts
- src/services/CliActions.ts
- src/services/DebuggerCheck.ts
- src/services/Dependencies.ts
- src/services/Scaffolder.ts
- src/services/TeamsToolkitIntegration.ts
- src/services/TerminalCommandExecuter.ts
The aim of this PR is to modify the extension so it will co-work better with Teams Toolkit.
When ACE component is present in the project the extension will suggest to install Adaptive Card Previewer 
Refactored Help & Feedback section to tree view with new Tools section with links to Teams Toolkit and Adaptive Card Previewer
Along the way refactored CI/CD action when sitecollection picked it now presents list of site level app catalogs to pick
Refactored all CLI actions to work in sub /src folder like in this example the upgrade action
Closes #131
Closes #133
> Add teams toolkit support. Closes: #131, #133

- CHANGELOG.md
- package-lock.json
- package.json
> Release v2.5.0

- README.md
- package-lock.json
- package.json
- src/constants/NodeVersionManagers.ts
- src/constants/index.ts
- src/services/TerminalCommandExecuter.ts
Adds support for NVM, NVS, or no Node Version Manager, and a VS Code Setting to control the choice. As discussed with @VesaJuvonen, needed for upcoming SPFx workshops.
Added a VSCode setting, and logic to change the command when launching a new terminal.
No issues man, we're all good!
> Support for NVS (#180)

- README.md
- assets/walkthrough/tasks-and-actions.md
- src/panels/CommandPanel.ts
Solve #209, and to give @Adam-it a PR as B-day present 🥳 🎈 
Closes: #209
> [Feature]: refactor the action naming, Closes #209

- src/webview/view/components/forms/spfxProject/AdditionalStep.tsx
- src/webview/view/components/forms/spfxProject/ComponentDetailsStep.tsx
- src/webview/view/components/forms/spfxProject/FormActions.tsx
- src/webview/view/components/forms/spfxProject/FormHeader.tsx
- src/webview/view/components/forms/spfxProject/GeneralInfoStep.tsx
- src/webview/view/components/forms/spfxProject/PackageSelector.tsx
- src/webview/view/components/forms/spfxProject/ScaffoldSpfxProjectView.tsx
- src/webview/view/components/forms/spfxProject/StepHeader.tsx
- src/webview/view/components/forms/spfxProject/index.ts
> This PR refactors scaffolding form to smaller components
> ![image](https://github.com/pnp/vscode-viva/assets/18114579/fcbf9fcc-18b9-44c6-9b96-62eaf206a0f2)
> Closes: #221
> Refactors scaffolding form to smaller components. Closes #221

- assets/walkthrough/create-new-project.md
Improves create new project walkthrough step with SPFx component types.
Closes: #267
> Improve create new project walkthrough step. Closes #267

- src/extension.ts
- src/services/Dependencies.ts
- src/services/TerminalCommandExecuter.ts
The aim is to refactor the way start and run commands in integrated VS Code terminal. The idea is to aling the approach by using the dedicated Terminal service which was developed for exactly that.
Closes: #246
> Updates terminal usage to use TerminalCommandExecuter service. Closes: #246

- src/chat/PromptHandlers.ts
- src/panels/CommandPanel.ts
- src/services/actions/CliActions.ts
- src/services/dataType/ProjectInformation.ts
- src/webview/PnPWebview.ts
- src/webview/view/components/forms/workflow/ScaffoldWorkflowView.tsx
- src/webview/view/index.tsx
The aim is to hide actions that require being signed in and validate if SPFx project in chat actions
// TODO
Closes:  #263
> Hide toolkit features that require signed in. Closes:  #263

- src/services/executeWrappers/CliCommandExecuter.ts
Adding the m365 prefix: The m365 prefix is now included before every CLI command, ensuring that the logged commands accurately reflect what is run in the terminal.
Logging CLI command options: The PR also includes the functionality to log the options passed with each command, providing better transparency and guidance for developers who want to understand the equivalent terminal commands for SPFx Toolkit features.
However, the functionality to set json as the default output for all commands was not implemented, as there are parts of the code that use other output formats, such as md (Markdown). Changing the default output to json globally could break those functionalities.
- [] not done
Closes: #283
> feat: :sparkles: Include m365 prefix and log passed CLI command options

- package.json
- src/panels/CommandPanel.ts
- src/utils/getExtensionSettings.ts
The aim is to do a bit of refactor to ensure correct types when retrieving extension settings
Closes: #317
> Refactors to ensure types for settings. Closes #317

- package.json
- src/services/actions/CliActions.ts
Adding the tour options and both md & tour options as settings for the upgrade and validate actions
Closes: #188
> Added tour response for Upgrade and Validate actions, Closes #188

- src/services/actions/CliActions.ts
> Prompts for a confirmation before removing an app from the app catalog to prevent accidental removals and improve user experience.
> ![image](https://github.com/user-attachments/assets/967a48f7-a73c-457e-8dd1-6f61917b915b)
> Closes: #349
> Prompts for confirmation before removing an app from app catalog. 

- README.md
- assets/walkthrough/tenant-details.md
- package.json
- src/constants/Commands.ts
- src/constants/ContextKeys.ts
- src/panels/CommandPanel.ts
- src/services/actions/CliActions.ts
> Upgrades an app to the latest version available in the app catalog for the specified site
> ![image](https://github.com/user-attachments/assets/3c9255b0-28de-4365-9bce-d12452c611be)
> Closes: #351
> Upgrades an app to the latest version available in the app catalog

- src/panels/CommandPanel.ts
- src/services/actions/CliActions.ts
> Improves upgrade app action by allowing users to specify only the relative path and then concatenate it under the hood with the tenant URL
> ![image](https://github.com/user-attachments/assets/6699f07d-ce5c-45d0-bfaf-5dd26e744bac)
Closes: #359
> Improves upgrade app action. Closes #359

- src/extension.ts
- src/providers/AuthProvider.ts
- src/services/actions/EntraAppRegistration.ts
The aim improve and simplify login behavior for SPFx Toolkit and try to fixup a strange issue with login output when cli command is executed.
Closes #342, #374
> Improves re-login experience. Closes #342, #374

- src/chat/PromptHandlers.ts
- src/constants/Prompts.ts
The aim is to update the command output mode to default to `text` for `list` CLI for Microsoft 365 commands and `md` for `get` commands
Closes: #375
> Updates /manage chat command to use text output mode for list CLI for M365 commands. Closes: #375

- src/constants/ProjectFileContent.ts
- src/extension.ts
- src/models/SpfxScaffoldCommandInput.ts
- src/services/actions/Scaffolder.ts
- src/webview/view/components/forms/spfxProject/AdditionalStep.tsx
- src/webview/view/components/forms/spfxProject/ScaffoldSpfxProjectView.tsx
The aim is to add SPFx fast serve support to project scaffolding so that it may be selected in as and optional dependency to install and configure
Closes: #218
> Adds fast serve optional step to scaffolding form. Closes #218

- package.json
- src/constants/Commands.ts
- src/panels/CommandPanel.ts
- src/services/actions/CliActions.ts
Adds 'Set Form Customizer' command to the SharePoint Framework Toolkit, to set the view, edit or new form with a form customizer
https://github.com/user-attachments/assets/1ac118ed-ad4b-44bb-946f-94c228aa0d81
Closes #348
> 🚀 Adds 'Set Form Customizer' command to the SharePoint Framework Toolkit, Closes #348

- src/services/actions/CliActions.ts
Includes check output window for CLI Actions
Closes #286
> 🚀 Enhance progress notifications with output window links for better user guidance, Closes #286

- src/constants/ProjectFileContent.ts
- src/extension.ts
- src/models/SpfxScaffoldCommandInput.ts
- src/services/actions/Scaffolder.ts
- src/webview/view/components/forms/spfxProject/AdditionalStep.tsx
- src/webview/view/components/forms/spfxProject/ScaffoldSpfxProjectView.tsx
This pull request adds logic to the new project scaffolding form to handle the actions that you can take when selecting a component type
https://github.com/user-attachments/assets/53021583-8e13-4147-8e0c-dea2be9c5337
Added conditions for extension component type
Added condition for webpart component type
Added React and ReactDom option for Extension runtime install
> each PR should be linked with a related issue [Remove this line]
Closes: #216
> scaffolding conditional logic form and react option

- src/services/actions/Dependencies.ts
The aim is to fix wrong warning message regarding Node version
Closes: #395
> Fixes node version warning message. Closes #395

- package.json
- src/panels/CommandPanel.ts
This PR refactors the tenant wide extensions logic to control the display of the app catalogs and the expansion of those if the setting is enabled
> clarify what was done and what still needs to be finished ex. [Remove this line]
Closes: #325
> refactor tenant wide extensions for app catalog toggle

- .github/workflows/check-tests.yml
- .vscode-test.mjs
- .vscode/launch.json
- npm-shrinkwrap.json
- package.json
- src/test/runTests.ts
- src/test/suite/extension.test.ts
- src/test/suite/index.ts
- tsconfig.json
The aim is to prototype integration tests for the solution
To debug tests:
1. install extension https://marketplace.visualstudio.com/items?itemName=ms-vscode.extension-test-runner
2. run `npm run package && npm run compile-tests`
3. run `Extension Tests` in debug
To run:
1. run `npm run package && npm run compile-tests`
2. run `npm run test` and check the result in terminal
Related #279
> Adds testing prototype solution. Related #279

- package.json
The aim is to make the VS Code extension commands shorter
Closes: #421
> Shorten command category names. Closes #421

- .github/workflows/check-tests.yml
- .github/workflows/release-beta.yml
- .github/workflows/release-docs.yml
- .github/workflows/release-local.yml
- .github/workflows/release.yml
- .github/workflows/update-samples.yml
The aim is to address security issues with workflows we used. 
Along the way I also added a condition so that the workflows will only run in the context of our repo and not on the forked repos as well.
docs -> https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idif
Since GitHub workflows run based on repo default branch we should merge this to `main` branch so it will resolve the security issues ASAP.
> Increase security in GitHub Workflows.

- package.json
To fix the issue #474, to shorten the command prefix from 'SharePoint Framework Toolkit' to 'SPFx Toolkit' for all actions.
Now all the commands in the command palette is adhering to 'SPFx Toolkit' as shown below. 
updated the view and activitybar container name & title to `SPFx Toolkit`  in `package.json` to make it consistent. 
- [] not done
Closes: #474
> 💡Fix:474-Shorten command name in command palette

- package.json
- src/panels/CommandPanel.ts
To align the command icons on both Tree view and the command palette
Old Icons are as below, 
New Icons are as below, 
Below are the details about the Icons
Gulp Task | Icon | Icon Label
-- | -- | --
Build Project | $(gear) | gear 
Bundle Project  | $(package) | package
Package Solution | $(zap) | zap
Publish Solution | $(rocket) | rocket
Clean Solution | $(clear-all) | clear-all
Test | $(beaker) | beaker 
Trust Dev Certificate | $(verified) | verified 
Deploy to Azure Storage | $(cloud-upload) | cloud-upload (deploy)
Changed the Icons on both `CommandPanel.ts` and `package.json`
- [] not done
Closes: #490
> Fix-490-Align command icons for gulp tasks

- package.json
- src/constants/Commands.ts
- src/constants/ContextKeys.ts
- src/panels/CommandPanel.ts
- src/services/actions/CliActions.ts
Soooooo, i did a little oopsie woopsie and totally broke the other PR 😅 
This feature adds the possibility to add a tenant app catalog of it doesn't exist and the possibility to add or remove a site app catalog
> clarify what was done and what still needs to be finished ex. [Remove this line]
Closes: #360
> Add tenant app catalog & add/remove site app catalog. Closes #360

- package.json
- src/services/actions/CliActions.ts
This PR adds support for configuring the shell type for `SPFx project upgrade` action. This setting allows users to specify their preferred shell when generating upgrade steps.
Closes: #525
> Adds new settings to set shell type for spfx project upgrade command. Closes #525

- scripts/cli-for-microsoft365-copy-local-version.ps1
The aim is to perform clean up of CLI for Microsoft 365 npm package not to include any docs, spec.js and js.map files in the final vs code extension bundle
> Adds CLI for Microsoft 365 package clean up

- src/webview/view/hooks/useSamples.tsx
Adds try catch block for tags and authors filtering to prevent future errors if some of those collections will be defined in json as `null` instead of `[]`
Closes: #603
> Adds try catch safe guards in sample gallery. Closes #603
